set(_CATKIN_CURRENT_PACKAGE "icub_upperbody")
set(icub_upperbody_VERSION "0.2.0")
set(icub_upperbody_MAINTAINER "MoveIt Setup Assistant <assistant@moveit.ros.org>")
set(icub_upperbody_PACKAGE_FORMAT "1")
set(icub_upperbody_BUILD_DEPENDS "icub_description")
set(icub_upperbody_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "icub_description")
set(icub_upperbody_BUILDTOOL_DEPENDS "catkin")
set(icub_upperbody_BUILDTOOL_EXPORT_DEPENDS )
set(icub_upperbody_EXEC_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "icub_description")
set(icub_upperbody_RUN_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "icub_description")
set(icub_upperbody_TEST_DEPENDS )
set(icub_upperbody_DOC_DEPENDS )
set(icub_upperbody_DEPRECATED "")